# Bug Report

## Description

- **What happened**? Describe the issue or unexpected behavior.
- **When did it happen**? Include specific steps to reproduce or a timeline.
- **Where did it happen**? Mention the specific part of the system (e.g., API, Docker integration, etc.).
- **Why is it a problem**? What impact does this bug have on the system?

## Steps to Reproduce

1. Step 1
2. Step 2
3. Step 3
4. Add more steps if necessary

## Expected Behavior

- What **should** happen if everything works correctly?

## Actual Behavior

- What **actually** happened?

## Logs and Error Messages

- Paste any relevant error messages, stack traces, or logs here.
- If applicable, include Docker logs, server logs, or API responses.

## Environment

- **Operating System**: (e.g., Ubuntu 20.04, Windows 10)
- **Docker Version**: (e.g., 20.10.7)
- **Backend Version**: (e.g., 1.0.0)
- **Node.js Version**: (e.g., 14.x)

## Additional Information

- Any additional context, screenshots, or details that could help identify the root cause of the issue.
